### ISSUE TITLE
Numerous memory leaks and 250MiB allocation to NativoSDK

### ISSUE THREAD

**Issue by p-canniff** [NativoPlatform/NativoSDK-iOS-SampleApps#4]
<img width="1795" alt="Screenshot 2024-09-03 at 8 58 35 AM" src="https://github.com/user-attachments/assets/507ddb71-8f5f-4846-878b-51df3d5a1464">
<img width="1799" alt="Screenshot 2024-09-03 at 8 58 49 AM" src="https://github.com/user-attachments/assets/4adc3897-377b-4bcf-a3ed-66de1e003741">

While working with the new 7.2.0 SDK (previously on 6.0) I noticed a large allocation spike on load of the NativoSDK. While at first I thought it may be a symptom of our implementation, it is now clear this is happening in your KMP rewrite.

I have provided above screenshots from the Leaks profiler in Xcode of your TableView Swift SampleApp where the leak can also be observed without any other dependencies. 

I can only provide a hunch, but I would use care in how the sharedInstance of the SDK is being handled around coroutines and review memory diffs as your proceed with 7.2.1.

Thanks

**Comment by MattMur** [comment]
Thanks for reporting this. Can you describe the steps within the app you took to arrive at this leak? What did you click, how far down did you scroll, etc.

**Comment by p-canniff** [comment]
I simply turned it on and ran it on a real device.

iPad Pro on iPad OS 16.6
iPhone 11 Pro on iOS 17.5.1

The images above are directly from the Nativo Sample App, CMD+i to open instruments, select leaks, and begin.

**Comment by MattMur** [comment]
Most of these leaks should now be fixed with update 7.2.1. Due to the nature of KMP garbage collector there seem to be a few leaks that still linger, but the largest ones have been fixed.
